variant = "loose"

[[issues]]
file = "src/Exception/ExceptionInterface.php"
code = "missing-api-or-internal"
message = 'Interface `Contenir\Mail\Exception\ExceptionInterface` is missing an `@api` or `@internal` annotation.'
count = 1

[[issues]]
file = "src/Mime/Exception/ExceptionInterface.php"
code = "missing-api-or-internal"
message = 'Interface `Contenir\Mail\Mime\Exception\ExceptionInterface` is missing an `@api` or `@internal` annotation.'
count = 1

[[issues]]
file = "src/Mime/Exception/InvalidArgumentException.php"
code = "class-must-be-final"
message = 'Class `Contenir\Mail\Mime\Exception\InvalidArgumentException` should be declared `final`.'
count = 1

[[issues]]
file = "src/Mime/Exception/RuntimeException.php"
code = "class-must-be-final"
message = 'Class `Contenir\Mail\Mime\Exception\RuntimeException` should be declared `final`.'
count = 1

[[issues]]
file = "src/Mime/Mime.php"
code = "impossible-condition"
message = "Redundant ternary operator: condition is always falsy."
count = 1

[[issues]]
file = "src/Mime/Mime.php"
code = "possibly-null-operand"
message = "Possibly null left operand used in string concatenation (type `null|string`)."
count = 1

[[issues]]
file = "src/Mime/Mime.php"
code = "possibly-undefined-int-array-index"
message = "Possibly undefined array key `non-negative-int` accessed on `array{0: non-empty-string}`."
count = 1

[[issues]]
file = "src/Mime/Mime.php"
code = "possibly-undefined-int-array-index"
message = "Possibly undefined array key `non-negative-int` accessed on `array{0: string('')}`."
count = 2

[[issues]]
file = "src/Mime/Mime.php"
code = "possibly-undefined-int-array-index"
message = "Possibly undefined array key `non-negative-int` accessed on `array{0: string, ...<non-negative-int, string>}`."
count = 2

[[issues]]
file = "src/Mime/Mime.php"
code = "redundant-comparison"
message = "Redundant `===` comparison: left-hand side is never identical to right-hand side."
count = 1
